### ISSUE TITLE
 linq could not be translated

### ISSUE THREAD

**Issue by eren186** [DevExpress/DevExtreme.AspNet.Data#420] opened 2020-04-10 06:47 UTC
hi guys
when i use searchpanel to filter my remote Repository like this below then i got error message "could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync()"
my devexpress.asp.net.datasourceloader version is 2.6.1 & EF CORE version Is 3.1
i had try #413 sloution but not work.
how can i solve it .

```csharp
public async Task<LoadResult> GetAllWithDDS([FromBody]DataSourceLoadOptions loadOptions)
{
   var tesT1s = from o in _tesT1Repository.GetAll()
               .Include( e => e.UserFk)
               .Include( e => e.OrganizationUnitFk)
                join o1 in _lookup_userRepository.GetAll() on o.UserId equals o1.Id into j1
                from s1 in j1.DefaultIfEmpty()
                join o2 in _lookup_organizationUnitRepository.GetAll() on o.OrganizationUnitId equals o2.Id into j2
                from s2 in j2.DefaultIfEmpty()
                select new TEST1WithDDSDto {
                       aa = o.aa,
                      Id = o.Id,
                    UserName = s1 == null ? "" : s1.Name.ToString(),
                    OrganizationUnitDisplayName = s2 == null ? "" : s2.DisplayName.ToString()
               };
     var result = await DataSourceLoader.LoadAsync(tesT1s, loadOptions);
   return result;
}
```

error code

```
ERROR 2020-03-29 18:22:14,971 [4    ] Mvc.ExceptionHandling.AbpExceptionFilter - The LINQ expression 'DbSet<TEST1>
    .Where(t => __ef_filter__p_0 || ((IMayHaveTenant)t).TenantId == __ef_filter__CurrentTenantId_1)
    .LeftJoin(
        outer: DbSet<User>
            .Where(u => __ef_filter__p_2 || !(((ISoftDelete)u).IsDeleted) && __ef_filter__p_3 || ((IMayHaveTenant)u).TenantId == __ef_filter__CurrentTenantId_4), 
        inner: t => t.UserId, 
        outerKeySelector: u => (Nullable<long>)u.Id, 
        innerKeySelector: (t, u) => new TransparentIdentifier<TEST1, User>(
            Outer = t, 
            Inner = u
        ))
    .LeftJoin(
        outer: DbSet<OrganizationUnit>
            .Where(o => __ef_filter__p_5 || !(((ISoftDelete)o).IsDeleted) && __ef_filter__p_6 || ((IMayHaveTenant)o).TenantId == __ef_filter__CurrentTenantId_7), 
        inner: ti => ti.Outer.OrganizationUnitId, 
        outerKeySelector: o => (Nullable<long>)o.Id, 
        innerKeySelector: (ti, o) => new TransparentIdentifier<TransparentIdentifier<TEST1, User>, OrganizationUnit>(
            Outer = ti, 
            Inner = o
        ))
    .Where(ti0 => EF.Property<Nullable<long>>(ti0.Outer.Inner, "Id") == null ? "" : ti0.Outer.Inner.Name.ToString().Contains("3") || EF.Property<Nullable<long>>(ti0.Inner, "Id") == null ? "" : ti0.Inner.DisplayName.ToString().Contains("3") || ti0.Outer.Outer.aa.Contains("3"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
System.InvalidOperationException: The LINQ expression 'DbSet<TEST1>
    .Where(t => __ef_filter__p_0 || ((IMayHaveTenant)t).TenantId == __ef_filter__CurrentTenantId_1)
    .LeftJoin(
        outer: DbSet<User>
            .Where(u => __ef_filter__p_2 || !(((ISoftDelete)u).IsDeleted) && __ef_filter__p_3 || ((IMayHaveTenant)u).TenantId == __ef_filter__CurrentTenantId_4), 
        inner: t => t.UserId, 
        outerKeySelector: u => (Nullable<long>)u.Id, 
        innerKeySelector: (t, u) => new TransparentIdentifier<TEST1, User>(
            Outer = t, 
            Inner = u
        ))
    .LeftJoin(
        outer: DbSet<OrganizationUnit>
            .Where(o => __ef_filter__p_5 || !(((ISoftDelete)o).IsDeleted) && __ef_filter__p_6 || ((IMayHaveTenant)o).TenantId == __ef_filter__CurrentTenantId_7), 
        inner: ti => ti.Outer.OrganizationUnitId, 
        outerKeySelector: o => (Nullable<long>)o.Id, 
        innerKeySelector: (ti, o) => new TransparentIdentifier<TransparentIdentifier<TEST1, User>, OrganizationUnit>(
            Outer = ti, 
            Inner = o
        ))
    .Where(ti0 => EF.Property<Nullable<long>>(ti0.Outer.Inner, "Id") == null ? "" : ti0.Outer.Inner.Name.ToString().Contains("3") || EF.Property<Nullable<long>>(ti0.Inner, "Id") == null ? "" : ti0.Inner.DisplayName.ToString().Contains("3") || ti0.Outer.Outer.aa.Contains("3"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

i had modify a sample for your guys to test.

WebApplication1.zip

**Comment by AlekseyMartynov** [comment] 2020-04-10 14:12
Hello

The following modification of the `select` clause should resolve the issue:

```c#
select new {
    aa = o.aa,
    Id = o.Id,
    UserName = s1.UserFk.DisplayName,
    OrganizationUnitDisplayName = s2.OrganizationUnitFk.Name
};
```

I noticed that this issue is a duplicate of the support ticket `T875049`. I kindly ask you (or your team) to avoid cross-posting issues in the future. This will save time and allow us to process all your inquiries in the most efficient manner.

Feel free to contact DevExpress Support if you have any further questions.

**Closed by AlekseyMartynov** 2020-04-10 14:12 UTC
