### ISSUE TITLE
Typescript Error from Angular 5 CLI

### ISSUE THREAD

**Issue by Horizont77** [DevExpress/DevExtreme.AspNet.Data#168] opened 2017-12-30 20:22 UTC
I get errors with Angular 5 CLI

ERROR in node_modules/devextreme-aspnet-data/js/dx.aspnet.data.d.ts(18,54): error TS2304: Cannot find name 'JQueryAjaxSettings'.

**Comment by AlekseyMartynov** [comment] 2017-12-30 20:52
Duplicate of https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/91#issuecomment-274453468

**Closed** 2018-01-09 08:33 UTC

**Comment by AntonSermyazhko** [comment] 2018-01-11 13:19
Horizont77, I've found that adding:
```
{
  ...
  "include": [
    "node_modules/@types/jquery"
  ]
}
```
in "tsconfig.json" solves the problem.
In the future, we are planning to deprecate the use of "jquery" in "devextreme-aspnet-data".

**Comment by dasois** [comment] 2018-01-30 14:42
doesn't work for me on a fresh angular-cli project

**Comment by AlekseyMartynov** [comment] 2018-01-30 16:25
@dasois 
We are very close to releasing a jQuery-free npm package.
PR #178 is merged.

Try a [CI build](https://ci.appveyor.com/project/dxrobot/devextreme-aspnet-data/build/404/artifacts):

```bash
npm i https://ci.appveyor.com/api/buildjobs/4jdis8ted8so9hm2/artifacts/devextreme-aspnet-data-nojquery-99.0.0-ci-000404.tgz
```

Usage:

```js
const AspNetData = require('devextreme-aspnet-data-nojquery');
```

**Comment by dasois** [comment] 2018-01-31 08:28
In Angular `const AspNetData = require('devextreme-aspnet-data-nojquery');` leads to a `error TS2304: Cannot find name 'require'.`.

I switched to `import * as AspNetData from 'devextreme-aspnet-data-nojquery';` and now it compiles successfully.

But running with `'https://js.devexpress.com/Demos/Mvc/api/DataGridWebApi'` I get a `Uncaught SyntaxError: Unexpected token :`

**Comment by AlekseyMartynov** [comment] 2018-01-31 11:44
Thanks @dasois 
I found that there's a problem with cross-domain requests.
It will be fixed in DevExtreme: https://github.com/DevExpress/DevExtreme/issues/2770
[Including jQuery](https://github.com/DevExpress/devextreme-angular#jquery-integration) can help until the fix is shipped.

**Comment by AlekseyMartynov** [comment] 2018-02-16 15:48
Hello @Horizont77 @dasois 
We have published a release candidate of [devextreme-aspnet-data-nojquery](https://www.npmjs.com/package/devextreme-aspnet-data-nojquery).
We would appreciate if you test this build and drop us a line in ticket #200.
